### ISSUE TITLE
Treeview-related Exception when "Save as..."

### ISSUE THREAD

**Issue by haesleinhuepf** [scijava/script-editor#31]
Hey all, hey @acardona,

I think the following bug is related to the new script editor which was just released. I have a single folder with macro files in the treeview on the left and opened one of the files by double-clicking. Then, I saved that file under a new name in the same folder. I guess the tree on the left tried to refresh then. While/after saving, this exception pops up:

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 29 >= 29
	at java.util.Vector.elementAt(Vector.java:477)
	at javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:245)
	at org.scijava.ui.swing.script.FileSystemTree$Node.getChildAt(FileSystemTree.java:182)
	at org.scijava.ui.swing.script.FileSystemTree$Node.getChildAt(FileSystemTree.java:93)
	at javax.swing.tree.DefaultTreeModel.getChild(DefaultTreeModel.java:174)
	at javax.swing.plaf.basic.BasicTreeUI.getLastChildPath(BasicTreeUI.java:1721)
	at javax.swing.plaf.basic.BasicTreeUI.paintVerticalPartOfLeg(BasicTreeUI.java:1429)
	at javax.swing.plaf.metal.MetalTreeUI.paintVerticalPartOfLeg(MetalTreeUI.java:211)
	at javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1203)
	at javax.swing.plaf.metal.MetalTreeUI.paint(MetalTreeUI.java:169)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I'm running on a recently updated Fiji on Windows 10, 64 bit. I'm happy to help fixing it, but I have no time right now.

Cheers,
Robert

**Comment by acardona** [comment]
I can't reproduce it in Ubuntu, but I have a reasonable idea of where to start. Basically, there's a synchronization point missing somewhere, and a list is being updated on the basis of old information while also using new information, hence the out of bounds error.

**Comment by haesleinhuepf** [comment]
Let me know if I can help! 🙂

**Comment by acardona** [comment]
Hi @haesleinhuepf, could you test this fix and see if it helps? It should; logically there was an issue and a lack of synchronization error could lead to the ArrayIndexOutOfBoundsException that you reported.

**Comment by acardona** [comment]
Hi @haesleinhuepf is this issue fixed for you?

**Comment by haesleinhuepf** [comment]
Hey @acardona ,

yes! Thanks :-)
