### ISSUE TITLE
BadLocationException in Python Auto-completion

### ISSUE THREAD

**Issue by haesleinhuepf** [scijava/script-editor#49]
Hi @acardona ,

when hitting CTRL+Space behind a single line containing "Views", a BadLocationException pops up:
```
javax.swing.text.BadLocationException: No such line
	at javax.swing.JTextArea.getLineStartOffset(JTextArea.java:409)
	at org.scijava.ui.swing.script.autocompletion.JythonAutoCompletion.insertCompletion(JythonAutoCompletion.java:74)
	at org.fife.ui.autocomplete.AutoCompletion.insertCompletion(AutoCompletion.java:609)
	at org.fife.ui.autocomplete.AutoCompletion.lambda$refreshPopupWindow$1(AutoCompletion.java:881)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![image](https://user-images.githubusercontent.com/12660498/100588569-52f20800-32f2-11eb-872c-b98ec3b44664.png)

Let me know if I can help fixing it!

Cheers,
Robert

**Comment by acardona** [comment]
Thanks, will fix. As a quick workaround, leave an empty line at the beginning of the script.

I suspect the issue is that lines in the RSyntaxArea may be 1-based and not 0-based.

Albert
