### ISSUE TITLE
IllegalStateException with IJ1 macro code in Script Interpreter

### ISSUE THREAD

**Issue by imagejan** [scijava/script-editor#8]
When trying to run IJ1 macro code in the script interpreter, e.g. `run("Blobs (25K)");`, the following exception is thrown:

```
java.lang.IllegalStateException: Cannot run macro from the EDT!
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:977)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1035)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:97)
	at org.scijava.script.DefaultScriptInterpreter.eval(DefaultScriptInterpreter.java:139)
	at org.scijava.script.DefaultScriptInterpreter.interpret(DefaultScriptInterpreter.java:198)
	at org.scijava.script.ScriptREPL.evaluate(ScriptREPL.java:182)
	at org.scijava.ui.swing.script.PromptPane.execute(PromptPane.java:157)
	at org.scijava.ui.swing.script.PromptPane.access$100(PromptPane.java:55)
	at org.scijava.ui.swing.script.PromptPane$1.keyPressed(PromptPane.java:80)
	at java.awt.Component.processKeyEvent(Component.java:6493)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ctrueden** [comment]
Thanks for the report, @imagejan. I was too lazy to investigate this problem before. It should now be fixed. However, there was a second problem with IJ1 macros in the REPL, which is fixed by imagej/imagej-legacy@c6e8176ef640b2b9e9a03719c822508b6875f96a.

One easy way to try this out is with my new [jrun](https://github.com/ctrueden/jrun) script:
```
jrun net.imagej:imagej-legacy:0.23.6-SNAPSHOT+org.scijava:script-editor:0.1.3-SNAPSHOT+net.imagej:imagej:2.0.0-rc-59
```
It does not use `mvn -U` (yet) though, so if it's not using the latest artifacts, you can first do:
```
mvn -U dependency:get -Dartifact=org.scijava:script-editor:0.1.3-SNAPSHOT
mvn -U dependency:get -Dartifact=net.imagej:imagej-legacy:0.23.6-SNAPSHOT
rm -rf ~/.jrun/net.imagej/imagej-legacy
```

If you prefer, you can use the CLI version of the REPL:
```
rm -rf ~/.jrun/net.imagej/imagej-legacy &&
jrun -Djava.awt.headless=true net.imagej:imagej-legacy:0.23.6-SNAPSHOT+net.imagej:imagej:2.0.0-rc-59:org.scijava.script.ScriptREPL
```
The `java.awt.headless` flag makes sure that ImageJ 1.x does not pop up dialog boxes in response to things like `print`.

Lastly, there are still a couple of quirks. E.g.:
```
> :lang ij1
language -> IJ1 Macro
> print(5)
5
<null>
> showMessage("Hello")
Hello
<null>
> showDialog("Hello")
Macro Error: Undefined identifier in line 93.

<showDialog> ( "Hello" )
<null>
>
```

Firstly, all eval statements from the IJ1 macro language return `null`. I am not sure how difficult it would be to change/fix that.

Secondly, when there is an error, the line number is vastly off, because the IJ1 macro language plugin secretly prepends a whole bunch of variable assignments, in order to inject the current variable bindings into each evaluation. Hence, the line numbers are wrong. We could intercept the error messages and fix the numbers, but it would be a little annoying to do. Probably we should change the injection to do everything on a single line, so the line number is at least only off by one, and thus easier to post-process.
