### ISSUE TITLE
Tab sizes > Other... throws exception

### ISSUE THREAD

**Issue by imagejan** [scijava/script-editor#9]
Running *Edit > Tab sizes > Other...* in the script editor throws the following exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.scijava.command.DynamicCommandInfo.populateItems(DynamicCommandInfo.java:303)
	at org.scijava.command.DynamicCommandInfo.<init>(DynamicCommandInfo.java:73)
	at org.scijava.command.DynamicCommand.getInfo(DynamicCommand.java:74)
	at org.scijava.command.DynamicCommand.getInfo(DynamicCommand.java:52)
	at org.scijava.module.DefaultModuleService.assignInputs(DefaultModuleService.java:460)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:241)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:210)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:199)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:184)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:186)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:169)
	at org.scijava.ui.swing.script.TextEditor.actionPerformed(TextEditor.java:1101)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by imagejan** [comment]
There are a [bunch of other classes](https://github.com/search?utf8=%E2%9C%93&q=DynamicCommand+is%3Aopen+user%3Afiji+user%3Aimagej+user%3Aimglib+user%3Ascijava&type=Code) that extend `DynamicCommand` but do not have any `@Plugin` annotation.

They might need to be changed in order to be picked up by the `CommandService`, no?
